### ISSUE TITLE
P61 torch.unint8

### ISSUE THREAD

**Issue by koheitokda** [Gin5050/deep-learning-with-pytorch-ja#11]
初版第1刷
P61 上から8行目
torch.unint8　ではなく　torch.uint8　ですね

**Comment by Gin5050** [comment]
koheitokda 様

再びご指摘いただきありがとうございます。
また、誤表記が多く申し訳ありません。

確認したところ、ご指摘の通りtorch.unint8 ではなくtorch.uint8が正しいです。

ご報告していただき誠にありがとうございます。
今後ともよろしくお願いいたします。
