### ISSUE TITLE
5.5.3項が存在しない

### ISSUE THREAD

**Issue by koheitokda** [Gin5050/deep-learning-with-pytorch-ja#12]
初版第1刷

P155 5.5.2項
P167 5.5.4項

**Comment by Gin5050** [comment]
koheitokda 様

ご指摘ありがとうございます。

おっしゃる通り5.5.3項が飛んでますね。
こちらも誤植として記録しておきます。

ご報告していただき誠にありがとうございます。
今後ともよろしくお願いいたします。
