### ISSUE TITLE
p73 図3.6につきまして

### ISSUE THREAD

**Issue by yosuke7040** [Gin5050/deep-learning-with-pytorch-ja#16]
書籍第3版になります。
p73 図3.6につきまして、左上図のテンソルですが
[[3, 1, 2],
 [4, 1, 1]]
となっておりますが
[[3, 1, 2],
 [4, 1, 7]]
ではないでしょうか?
ご確認よろしくお願い致します。

**Comment by Gin5050** [comment]
yosuke7040様

ご連絡いただきありがとうございます。
ご指摘いただいた通り、誤植です。
正しくはyosuke7040様が書いたいただいたように
[[3, 1, 2],
[4, 1, 7]]
です。

お知らせいただき誠にありがとうございます。

本Issueに誤植ラベルを貼り付け、他の読者の方の参考にもさせてください。
お時間をとり、Issueに挙げて頂いて誠にありがとうございます。
