### ISSUE TITLE
p68にある図3.5のストライドの説明

### ISSUE THREAD

**Issue by takosdev** [Gin5050/deep-learning-with-pytorch-ja#3]
p68にある図3.5のストライドの説明ですが、
「+1」が「次の行」、「+3」が「次の列」となっていますが、
「+1」が「次の列」、「+3」が「次の行」ではないでしょうか？
原書だと、「+1」が「NEXT COL」、「+3」が「NEXT ROW」となっていました。

**Comment by Gin5050** [comment]
takosdev様

返事が遅れてしまい申し訳ありません。
ご連絡ありがとうございます。

確認したところ、ご指摘の通り、こちらの誤植でした。

本Issueに誤植ラベルを付与し、他の読者の皆様への案内にさせてください。

お時間をいただき、Issueを立てて頂いて、誠にありがとうございます。
今後ともどうぞ宜しくお願い致します。

**Comment by takosdev** [comment]
Gin5050様
確認頂き、ありがとうございました。
