### ISSUE TITLE
P68 図3.5

### ISSUE THREAD

**Issue by koheitokda** [Gin5050/deep-learning-with-pytorch-ja#8]
P68 図3.5
- 右上「shape = (3,3)」が矢印に対し右にずれていますね
初版第1刷

**Comment by Gin5050** [comment]
koheitokda 様

ご指摘ありがとうございます。
また、ご連絡が遅くなり申し訳ありません。

おっしゃる通り矢印の位置が少しずれていました。
こちら誤植として記録しておきます。

ご報告していただき誠にありがとうございます。
今後ともよろしくお願いいたします。

**Comment by tkhgsh** [comment]
同じ図ですが、
「次の**行**(stride[1]=1)」とあるのは、正しくは「次の**列**（stride[1]=1)」
「次の**列**(stride[0]=3)」とあるのは、正しくは「次の**行**（stride[0]=3」
ではないでしょうか。
